version: '3.9'

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: SqlServerSplitQueryDemo
    environment:
      SA_PASSWORD: "YourStrong!Passw0rd"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    healthcheck:
      test: [ "CMD", "/opt/mssql-tools18/bin/sqlcmd", "-S", "localhost", "-U", "sa", "-P", "YourStrong!Passw0rd", "-Q", "SELECT 1", "-C" ]
      interval: 10s
      retries: 10
      
  app:
    build: .
    depends_on:
      - sqlserver
    environment:
      # Connection string with host as service name 'sqlserver'
      ConnectionStrings__DefaultConnection: "Server=sqlserver,1433;Database=SplitQueryDemo;User=sa;Password=YourStrong!Passw0rd;TrustServerCertificate=True;"

